# Generated by Django 4.2.1 on 2023-05-25 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='active_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Active Status')),
            ],
            options={
                'db_table': 'active_status',
            },
        ),
        migrations.CreateModel(
            name='entity_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Entity Type')),
            ],
            options={
                'db_table': 'entity_type',
            },
        ),
        migrations.CreateModel(
            name='gst_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='GST Status')),
            ],
            options={
                'db_table': 'gst_status',
            },
        ),
        migrations.CreateModel(
            name='industry_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Industry Name')),
            ],
            options={
                'db_table': 'industry_type',
            },
        ),
        migrations.CreateModel(
            name='mode_of_transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Mode of Transport')),
            ],
            options={
                'db_table': 'mode_of_transport',
            },
        ),
    ]
