# Generated by Django 4.2.1 on 2023-05-28 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0002_trip_invoice_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='trip_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Trip Status')),
            ],
            options={
                'db_table': 'trip_status',
            },
        ),
    ]
