# Generated by Django 4.2.1 on 2023-07-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0004_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='document_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Document Status')),
            ],
            options={
                'db_table': 'document_status',
            },
        ),
    ]
