# Generated by Django 4.2.1 on 2023-07-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0005_document_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Document Status')),
            ],
            options={
                'db_table': 'contract_status',
            },
        ),
    ]
