# Generated by Django 4.2.1 on 2023-05-25 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='service_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Service Class')),
            ],
            options={
                'db_table': 'service_class',
            },
        ),
        migrations.CreateModel(
            name='service_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Service Type')),
                ('service_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service_class', verbose_name='Service Class')),
            ],
            options={
                'db_table': 'service_type',
            },
        ),
        migrations.CreateModel(
            name='service_models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Model Name')),
                ('service_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service_class', verbose_name='Service Class')),
            ],
            options={
                'db_table': 'service_models',
            },
        ),
    ]
