# Generated by Django 4.2.1 on 2023-05-25 02:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('hub', '0001_initial'),
        ('classification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Project Name')),
                ('gstin', models.CharField(max_length=15, verbose_name='GSTIN')),
                ('billing_address', models.TextField(verbose_name='Billing Address')),
                ('shipping_address', models.TextField(verbose_name='Shipping Address')),
                ('shipping_city', models.CharField(max_length=32, verbose_name='Shipping City Name')),
                ('shipping_state', models.CharField(max_length=32, verbose_name='Shipping State Name')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Project Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Project End Date')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=32)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.city', verbose_name='City')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client', verbose_name='Client')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='classification.active_status', verbose_name='Active Status')),
            ],
            options={
                'db_table': 'project',
            },
        ),
    ]
