# Generated by Django 4.2.1 on 2023-07-02 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_delete_service_type'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='project',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='project',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='project',
            name='shipping_address',
        ),
        migrations.RemoveField(
            model_name='project',
            name='shipping_city',
        ),
        migrations.RemoveField(
            model_name='project',
            name='shipping_state',
        ),
        migrations.AddField(
            model_name='project',
            name='service_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='service.service_class'),
            preserve_default=False,
        ),
    ]
