import {
  DashboardOutlined,
  UserOutlined,
  SolutionOutlined,
  ShopOutlined,
  BarChartOutlined,
  FileTextOutlined,
  UsergroupAddOutlined,
} from "@ant-design/icons";

const MenuItems = [
  {
    key: "1",
    icon: <DashboardOutlined />,
    name: "MySpace",
    level: 0,
    link: "",
  },
  {
    key: "2",
    icon: <SolutionOutlined />,
    name: "Services",
    level: 0,
    link: "services",
    children: [
      {
        key: "2.1",
        icon: <SolutionOutlined />,
        name: "Transport",
        level: 0,
        link: "services/transport",
      },
      {
        key: "2.2",
        icon: <SolutionOutlined />,
        name: "Delivery",
        level: 0,
        link: "services/delivery",
      },
      {
        key: "2.3",
        icon: <SolutionOutlined />,
        name: "Warehouse",
        level: 0,
        link: "services/warehouse",
      },
    ],
  },
  {
    key: "3",
    icon: <UserOutlined />,
    name: "Clients",
    level: 1,
    link: "clients",
    children: [
      {
        key: "3.1",
        icon: <UserOutlined />,
        name: "Register",
        level: 2,
        link: "clients/register",
      },
      {
        key: "3.2",
        icon: <UserOutlined />,
        name: "Contracts",
        level: 2,
        link: "clients/contracts",
      },
      {
        key: "3.3",
        icon: <UserOutlined />,
        name: "Projects",
        level: 2,
        link: "clients/projects",
      },
      {
        key: "3.4",
        icon: <UserOutlined />,
        name: "Reports",
        level: 2,
        link: "clients/reports",
      },
      {
        key: "3.5",
        icon: <UserOutlined />,
        name: "Directory",
        level: 2,
        link: "clients/directory",
      },
    ],
  },
  {
    key: "4",
    icon: <ShopOutlined />,
    name: "Vendors",
    level: 1,
    link: "vendors",
    children: [
      {
        key: "4.1",
        icon: <ShopOutlined />,
        name: "Register",
        level: 2,
        link: "vendors/register",
      },
      {
        key: "4.2",
        icon: <ShopOutlined />,
        name: "Contracts",
        level: 2,
        link: "vendors/contracts",
      },
      {
        key: "4.3",
        icon: <ShopOutlined />,
        name: "Reports",
        level: 2,
        link: "vendors/report",
      },
    ],
  },
  {
    key: "5",
    icon: <BarChartOutlined />,
    name: "Finance",
    level: 2,
    link: "finance",
    children: [
      {
        key: "5.1",
        icon: <BarChartOutlined />,
        name: "Receivables",
        level: 2,
        link: "finance/receivable",
      },
      {
        key: "5.2",
        icon: <BarChartOutlined />,
        name: "Payables",
        level: 2,
        link: "finance/payables",
      },
      {
        key: "5.3",
        icon: <BarChartOutlined />,
        name: "Reports",
        level: 2,
        link: "finance/reports",
      },
      {
        key: "5.4",
        icon: <BarChartOutlined />,
        name: "Invoice Manager",
        level: 2,
        link: "finance/invoicemanager",
      },
    ],
  },
  {
    key: "6",
    icon: <FileTextOutlined />,
    name: "Reports",
    level: 0,
    link: "reports",
  },
  {
    key: "7",
    icon: <UsergroupAddOutlined />,
    name: "Users",
    level: 2,
    link: "users",
  },
];

export default MenuItems;
