# Generated by Django 4.2.1 on 2023-05-25 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Hub Name')),
                ('shortname', models.CharField(unique=True, verbose_name='Hub Short Name')),
            ],
            options={
                'db_table': 'hub',
            },
        ),
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='City Name')),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.hub')),
            ],
            options={
                'db_table': 'city',
            },
        ),
    ]
