# Generated by Django 4.2.1 on 2023-07-02 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_zones'),
    ]

    operations = [
        migrations.CreateModel(
            name='state',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='State')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hub.zones', verbose_name='Zone')),
            ],
            options={
                'db_table': 'state',
            },
        ),
    ]
