# Generated by Django 4.2.1 on 2023-05-28 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
        ('trips', '0003_alter_trips_table'),
        ('triplinks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='client_triplink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='invoice.client_invoice', verbose_name='Client Invoice ID')),
                ('trip_id', models.OneToOneField(max_length=32, on_delete=django.db.models.deletion.PROTECT, to='trips.trips', verbose_name='Trip ID')),
            ],
            options={
                'db_table': 'client_triplink',
            },
        ),
        migrations.CreateModel(
            name='vendor_triplink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='invoice.client_invoice', verbose_name='Vendor Invoice ID')),
                ('trip_id', models.OneToOneField(max_length=32, on_delete=django.db.models.deletion.PROTECT, to='trips.trips', verbose_name='Trip ID')),
            ],
            options={
                'db_table': 'vendor_triplink',
            },
        ),
        migrations.DeleteModel(
            name='client_trips',
        ),
    ]
