# Generated by Django 4.2.1 on 2023-05-25 02:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Client Name')),
                ('shortname', models.CharField(max_length=4, verbose_name='Client Short Name')),
                ('registered_office', models.TextField(verbose_name='Registered Office Address')),
                ('pan', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('[A-Za-z]{5}[0-9]{4}[A-Za-z]{1}')], verbose_name='PAN Number')),
                ('registration_number', models.CharField(max_length=30, verbose_name='Registration Number')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=32)),
                ('entity_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='classification.entity_type', verbose_name='Entity Type')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classification.industry_type', verbose_name='Industry Type')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='classification.active_status', verbose_name='Active Status')),
            ],
            options={
                'db_table': 'client',
            },
        ),
    ]
