# Generated by Django 4.2.1 on 2023-07-12 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='crf_file_id',
            field=models.FileField(null=True, upload_to='../../uploads/CRF'),
        ),
        migrations.AddField(
            model_name='client',
            name='pan_file_id',
            field=models.FileField(null=True, upload_to='../../uploads/PAN'),
        ),
    ]
