# Generated by Django 4.2.1 on 2023-07-22 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_client_crf_file_id_client_pan_file_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='registration_number',
            field=models.CharField(max_length=30, null=True, verbose_name='Registration Number'),
        ),
    ]
