# Generated by Django 4.2.1 on 2023-07-23 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_client_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='crf_file_id',
            field=models.FileField(null=True, upload_to='CRF'),
        ),
        migrations.AlterField(
            model_name='client',
            name='pan_file_id',
            field=models.FileField(null=True, upload_to='PAN'),
        ),
    ]
