# Generated by Django 4.2.1 on 2023-05-28 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0002_delete_service_type'),
        ('classification', '0003_trip_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='trip_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Service Type')),
                ('service_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service_class', verbose_name='Service Class')),
            ],
            options={
                'db_table': 'trip_type',
            },
        ),
        migrations.CreateModel(
            name='trips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_reporting_time', models.DateTimeField(verbose_name='Reporting Time')),
                ('trip_start_time', models.DateTimeField(blank=True, verbose_name='Trip Start Time')),
                ('trip_end_time', models.DateTimeField(blank=True, verbose_name='Trip End Time')),
                ('trip_start_km', models.FloatField(verbose_name='Start KM')),
                ('trip_end_km', models.FloatField(verbose_name='End KM')),
                ('replacement_trip_id', models.IntegerField(null=True, verbose_name='Replacement Trip ID')),
                ('trip_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classification.trip_status', verbose_name='Trip Status')),
                ('trip_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trips.trip_type', verbose_name='Trip Type')),
            ],
            options={
                'db_table': 'regular_trips',
            },
        ),
    ]
