# Generated by Django 4.2.1 on 2023-05-28 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_alter_trips_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='trips',
            table='trip',
        ),
    ]
