# Generated by Django 4.2.1 on 2023-07-04 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_alter_trips_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='adhoc_trip_rates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_client_rate', models.FloatField(verbose_name='Trip Client Rate')),
                ('trip_Vendor_rate', models.FloatField(verbose_name='Trip Vendor Rate')),
                ('trip_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.trips', verbose_name='Trip ID')),
            ],
        ),
    ]
