const demo = {
  Big: {
    description: "Demo Card",
    icon: "Demo",
    icon_color: "Yellow",
    caption: "Keep the smile",
    value: 1000,
    editable: false,
    growth: 100,
    show_details: true,
    summary: "This is how we keep you happy.",
    units: "U",
    size: "big",
  },
  Small: {
    icon: "Demo",
    icon_color: "Yellow",
    value: 1000,
    editable: false,
    units: "U",
    size: "small",
  },
  Wide: {
    description: "Demo Card",
    icon: "Demo",
    icon_color: "Yellow",
    caption: "Keep the smile",
    value: 1000,
    editable: false,
    growth: 100,
    show_details: true,
    units: "U",
    size: "wide",
  },
  Normal: {
    description: "Demo Card",
    icon: "Demo",
    icon_color: "Yellow",
    caption: "Keep the smile",
    value: 1000,
    editable: false,
    growth: 100,
    show_details: true,
    units: "U",
    size: "normal",
  },
};
