import {
  CheckCircleOutlined,
  CloseCircleOutlined,
  InfoCircleOutlined,
  ExclamationCircleOutlined,
  QuestionCircleOutlined,
  SearchOutlined,
  UserOutlined,
  LockOutlined,
  MailOutlined,
  PhoneOutlined,
  CalendarOutlined,
  FileOutlined,
  FolderOutlined,
  SettingOutlined,
  HomeOutlined,
  HeartOutlined,
  StarOutlined,
  TagOutlined,
  CameraOutlined,
  CloudOutlined,
  DownloadOutlined,
  UploadOutlined,
  EditOutlined,
  DeleteOutlined,
  CopyOutlined,
  UndoOutlined,
  RedoOutlined,
  LoadingOutlined,
  SmileFilled,
} from "@ant-design/icons";

const IconPicker = {
  CheckCircle: CheckCircleOutlined,
  CloseCircle: CloseCircleOutlined,
  InfoCircle: InfoCircleOutlined,
  ExclamationCircle: ExclamationCircleOutlined,
  QuestionCircle: QuestionCircleOutlined,
  Search: SearchOutlined,
  User: UserOutlined,
  Lock: LockOutlined,
  Mail: MailOutlined,
  Phone: PhoneOutlined,
  Calendar: CalendarOutlined,
  File: FileOutlined,
  Folder: FolderOutlined,
  Setting: SettingOutlined,
  Home: HomeOutlined,
  Heart: HeartOutlined,
  Star: StarOutlined,
  Tag: TagOutlined,
  Camera: CameraOutlined,
  Cloud: CloudOutlined,
  Download: DownloadOutlined,
  Upload: UploadOutlined,
  Edit: EditOutlined,
  Delete: DeleteOutlined,
  Copy: CopyOutlined,
  Undo: UndoOutlined,
  Redo: RedoOutlined,
  Loading: LoadingOutlined,
  Demo: SmileFilled,
} as const;

export { IconPicker };
