# Generated by Django 4.2.1 on 2023-05-26 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client_invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=16, unique=True, verbose_name='Number')),
                ('taxable_value', models.FloatField(verbose_name='Taxable Value')),
                ('cgst', models.FloatField(verbose_name='CGST')),
                ('sgst', models.FloatField(verbose_name='SGST')),
                ('igst', models.FloatField(verbose_name='IGST')),
                ('invoice_value', models.FloatField(verbose_name='Invoice Value')),
            ],
            options={
                'db_table': 'client_invoice',
            },
        ),
        migrations.CreateModel(
            name='vendor_invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=16, unique=True, verbose_name='Number')),
                ('taxable_value', models.FloatField(verbose_name='Taxable Value')),
                ('cgst', models.FloatField(verbose_name='CGST')),
                ('sgst', models.FloatField(verbose_name='SGST')),
                ('igst', models.FloatField(verbose_name='IGST')),
                ('invoice_value', models.FloatField(verbose_name='Invoice Value')),
            ],
            options={
                'db_table': 'vendor_invoice',
            },
        ),
    ]
