# Generated by Django 4.2.1 on 2023-07-02 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_invoice_request_remove_client_invoice_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice_request',
            name='request_remarks',
            field=models.TextField(default='', verbose_name='Request Remark'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice_requests_trips',
            name='extra_HR_rate',
            field=models.FloatField(default=0, verbose_name='Extra Hour Rate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice_requests_trips',
            name='extra_HR_unit',
            field=models.FloatField(default=0, verbose_name='Extra Hour Unit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice_requests_trips',
            name='extra_KM_rate',
            field=models.FloatField(default=0, verbose_name='Extra KM Rate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice_requests_trips',
            name='extra_KM_unit',
            field=models.FloatField(default=0, verbose_name='Extra KM Unit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice_requests_trips',
            name='loading_unloading_rate',
            field=models.FloatField(default=0, verbose_name='Loading Unloading Rate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice_requests_trips',
            name='loading_unloading_unit',
            field=models.FloatField(default=0, verbose_name='Loading Unloading Unit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice_requests_trips',
            name='toll_charges',
            field=models.FloatField(default=0, verbose_name='Toll Charges'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice_requests_trips',
            name='trip_value',
            field=models.FloatField(default=0, verbose_name='Trip Value'),
            preserve_default=False,
        ),
    ]
